In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets,tree


In [15]:
#loading then data
iris = datasets.load_iris()
X = iris.data #Collecting the input-features
Y = iris.target #collecting the output-features

#Splitiong the dataset into traning,testing and validation sets
number_of_sample = len(Y)
#Geting random indicies
random_indices = np.random.permutation(number_of_sample)

#Splitting training set
x_train = X[random_indices[:70]]
y_train = Y[random_indices[:70]]

#Sptittiong validation set
x_val = X[random_indices[70:85]]
y_val = Y[random_indices[70:85]]

#Splitting testing set
x_test = X[random_indices[85:]]
y_test = Y[random_indices[85:]]


In [16]:
#Creating the instances of Decision tree classifier class
model = tree.DecisionTreeClassifier()
model.fit(x_train,y_train)
#pridiction of model
model_prediction = model.predict(x_val)
print(model_prediction)
print(y_val)

[1 1 2 0 2 2 2 0 1 1 0 0 2 0 0]
[1 1 1 0 2 2 2 0 1 1 0 0 2 0 0]


In [17]:
#printing precentage of miss classificatin
validation_set_predictions = model.predict(x_val)#np array on validation set
test_set_predictions = model.predict(x_test)#np array on test set

validation_misclassification_percentage = 0
for i in range(len(validation_set_predictions)):
    if validation_set_predictions[i] != y_val[i]:
        validation_misclassification_percentage+=1
validation_misclassification_percentage *= 100/len(y_val)
print('validation misclassification percentage =', validation_misclassification_percentage, '%')


test_misclassification_percentage = 0
for i in range(len(test_set_predictions)):
    if test_set_predictions[i]!=y_test[i]:
        test_misclassification_percentage+=1
test_misclassification_percentage *= 100/len(y_test)
print('test misclassification percentage =', test_misclassification_percentage, '%')

#printing arary of evalaliting the validation and test set
print(validation_set_predictions)
print(test_set_predictions)

validation misclassification percentage = 6.666666666666667 %
test misclassification percentage = 0.0 %
[1 1 2 0 2 2 2 0 1 1 0 0 2 0 0]
[1 2 0 1 0 0 1 1 0 2 1 0 2 1 2 2 2 0 1 1 0 2 0 2 0 2 0 1 1 0 2 1 1 2 0 0 2
 1 2 2 2 0 0 2 2 0 1 0 0 1 1 2 0 0 1 1 2 2 0 1 1 1 2 2 1]


In [18]:
accuracy_val = model.score(x_val,y_val)
accuracy_test = model.score(x_test,y_test)
print("Validation Accuracy =",accuracy_val)
print("Test Accuracy =",accuracy_test)

Validation Accuracy = 0.9333333333333333
Test Accuracy = 1.0
